// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"

	"github.com/GuilhermeDeOliveiraAmorim/you-choose/internal/infra/database"
	"github.com/GuilhermeDeOliveiraAmorim/you-choose/internal/infra/web"
	"github.com/GuilhermeDeOliveiraAmorim/you-choose/internal/usecases"
)

func NewCreateChooserUseCaseGen(db *sql.DB) *usecases.ChooserUseCase {
	chooserRepository := database.NewChooserRepository(db)
	movieListRepository := database.NewMovieListRepository(db)
	movieRepository := database.NewMovieRepository(db)
	tagRepository := database.NewTagRepository(db)
	chooserUseCase := usecases.NewChooserUseCase(chooserRepository, movieListRepository, movieRepository, tagRepository)
	return chooserUseCase
}

func NewWebChooserHandlerGen(db *sql.DB) *web.WebChooserHandler{
	chooserRepository := database.NewChooserRepository(db)
	movieListRepository := database.NewMovieListRepository(db)
	movieRepository := database.NewMovieRepository(db)
	tagRepository := database.NewTagRepository(db)
	webChooserHandler := web.NewChooserHandler(chooserRepository, movieListRepository, movieRepository, tagRepository)
	return webChooserHandler
}

func NewCreateMovieListUseCaseGen(db *sql.DB) *usecases.MovieListUseCase {
	movieListRepository := database.NewMovieListRepository(db)
	chooserRepository := database.NewChooserRepository(db)
	movieRepository := database.NewMovieRepository(db)
	tagRepository := database.NewTagRepository(db)
	fileRepository := database.NewFileRepository(db)
	MovieListUseCase := usecases.NewMovieListUseCase(movieListRepository, chooserRepository, movieRepository, tagRepository, fileRepository)
	return MovieListUseCase
}

func NewWebMovieListHandlerGen(db *sql.DB) *web.WebMovieListHandler{
	movieListRepository := database.NewMovieListRepository(db)
	chooserRepository := database.NewChooserRepository(db)
	movieRepository := database.NewMovieRepository(db)
	tagRepository := database.NewTagRepository(db)
	fileRepository := database.NewFileRepository(db)
	webMovieListHandler := web.NewMovieListHandler(movieListRepository, chooserRepository, movieRepository, tagRepository, fileRepository)
	return webMovieListHandler
}

func NewCreateMovieUseCaseGen(db *sql.DB) *usecases.MovieUseCase {
	movieRepository := database.NewMovieRepository(db)
	actorRepository := database.NewActorRepository(db)
	writerRepository := database.NewWriterRepository(db)
	directorRepository := database.NewDirectorRepository(db)
	genreRepository := database.NewGenreRepository(db)
	movieListRepository := database.NewMovieListRepository(db)
	MovieUseCase := usecases.NewMovieUseCase(movieRepository, actorRepository, writerRepository, directorRepository, genreRepository, movieListRepository)
	return MovieUseCase
}

func NewWebMovieHandlerGen(db *sql.DB) *web.WebMovieHandler{
	movieRepository := database.NewMovieRepository(db)
	actorRepository := database.NewActorRepository(db)
	writerRepository := database.NewWriterRepository(db)
	directorRepository := database.NewDirectorRepository(db)
	genreRepository := database.NewGenreRepository(db)
	movieListRepository := database.NewMovieListRepository(db)
	webMovieHandler := web.NewMovieHandler(movieRepository, actorRepository, writerRepository, directorRepository, genreRepository, movieListRepository)
	return webMovieHandler
}

func NewCreateActorUseCaseGen(db *sql.DB) *usecases.ActorUseCase {
	actorRepository := database.NewActorRepository(db)
	movieRepository := database.NewMovieRepository(db)
	fileRepository := database.NewFileRepository(db)
	ActorUseCase := usecases.NewActorUseCase(actorRepository, movieRepository, fileRepository)
	return ActorUseCase
}

func NewWebActorHandlerGen(db *sql.DB) *web.WebActorHandler{
	actorRepository := database.NewActorRepository(db)
	movieRepository := database.NewMovieRepository(db)
	fileRepository := database.NewFileRepository(db)
	webActorHandler := web.NewActorHandler(actorRepository, movieRepository, fileRepository)
	return webActorHandler
}

func NewCreateWriterUseCaseGen(db *sql.DB) *usecases.WriterUseCase {
    writerRepository := database.NewWriterRepository(db)
    movieRepository := database.NewMovieRepository(db)
	fileRepository := database.NewFileRepository(db)
    WriterUseCase := usecases.NewWriterUseCase(writerRepository, movieRepository, fileRepository)
    return WriterUseCase
}

func NewWebWriterHandlerGen(db *sql.DB) *web.WebWriterHandler{
    writerRepository := database.NewWriterRepository(db)
    movieRepository := database.NewMovieRepository(db)
	fileRepository := database.NewFileRepository(db)
    webWriterHandler := web.NewWriterHandler(writerRepository, movieRepository, fileRepository)
    return webWriterHandler
}

func NewCreateDirectorUseCaseGen(db *sql.DB) *usecases.DirectorUseCase {
    directorRepository := database.NewDirectorRepository(db)
    movieRepository := database.NewMovieRepository(db)
	fileRepository := database.NewFileRepository(db)
    DirectorUseCase := usecases.NewDirectorUseCase(directorRepository, movieRepository, fileRepository)
    return DirectorUseCase
}

func NewWebDirectorHandlerGen(db *sql.DB) *web.WebDirectorHandler{
    directorRepository := database.NewDirectorRepository(db)
    movieRepository := database.NewMovieRepository(db)
	fileRepository := database.NewFileRepository(db)
    webDirectorHandler := web.NewDirectorHandler(directorRepository, movieRepository, fileRepository)
    return webDirectorHandler
}

func NewCreateGenreUseCaseGen(db *sql.DB) *usecases.GenreUseCase {
    genreRepository := database.NewGenreRepository(db)
    movieRepository := database.NewMovieRepository(db)
	fileRepository := database.NewFileRepository(db)
    GenreUseCase := usecases.NewGenreUseCase(genreRepository, movieRepository, fileRepository)
    return GenreUseCase
}

func NewWebGenreHandlerGen(db *sql.DB) *web.WebGenreHandler{
    genreRepository := database.NewGenreRepository(db)
    movieRepository := database.NewMovieRepository(db)
	fileRepository := database.NewFileRepository(db)
    webGenreHandler := web.NewGenreHandler(genreRepository, movieRepository, fileRepository)
    return webGenreHandler
}

func NewCreateTagUseCaseGen(db *sql.DB) *usecases.TagUseCase {
    tagRepository := database.NewTagRepository(db)
    movieListRepository := database.NewMovieListRepository(db)
	fileRepository := database.NewFileRepository(db)
    TagUseCase := usecases.NewTagUseCase(tagRepository, movieListRepository, fileRepository)
    return TagUseCase
}

func NewWebTagHandlerGen(db *sql.DB) *web.WebTagHandler{
    tagRepository := database.NewTagRepository(db)
    movieListRepository := database.NewMovieListRepository(db)
	fileRepository := database.NewFileRepository(db)
    webTagHandler := web.NewTagHandler(tagRepository, movieListRepository, fileRepository)
    return webTagHandler
}

func NewCreateFileUseCaseGen(db *sql.DB) *usecases.FileUseCase {
    fileRepository := database.NewFileRepository(db)
    FileUseCase := usecases.NewFileUseCase(fileRepository)
    return FileUseCase
}

func NewWebFileHandlerGen(db *sql.DB) *web.WebFileHandler{
    fileRepository := database.NewFileRepository(db)
    webFileHandler := web.NewFileHandler(fileRepository)
    return webFileHandler
}